language: node_js

script:
  - yarn test:ci

os:
  - linux

node_js:
  - "10"
  - "12"
  - "lts/*"

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - sudo cp dbus.conf /etc/dbus-1/system.d/dbus.conf
