language: node_js

script:
  - yarn test:ci

os:
  - linux
  - osx

node_js:
  - "10"
  - "12"
  - "lts/*"

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - cp dbus.xml /etc/dbus-1/system.d/dbus.xml
